package enums.enumsForBMW;

public enum MaxSpeedForBMW {
    TWO_HUNDRED_AND_SIXTY,
    TWO_HUNDRED_AND_SEVENTY,
    TWO_HUNDRED_AND_FIFTY,
    TWO_HUNDRED_AND_NINETY,
    THREE_HUNDRED,
    THREE_HUNDRED_AND_TEN;
}
